
service: RDSconnection

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  vpc:
    securityGroupIds:
      - sg-075bd49d50ca2f192    
    subnetIds:
      - subnet-02f886d30f9c26967
      - subnet-0cda6ab30269b661e
      - subnet-089ab30c5e38abef8
      - subnet-0e2e328687cc2d570
      - subnet-0e921e7f02c00aedf
      - subnet-0383221254e6d56c1 
           

functions:
  RDSTestConnection:
    handler: Handlers/handlerRDSTestConnection.RDSTestConnection
    events:
      - http:
          path: /RDSconnection/RDSTestConnection
          method: get

  RDScreate:
    handler: Handlers/handlerRDScreate.RDScreate
    events:
      - http:
          path: /RDSconnection/RDScreate
          method: post

  RDSupdate:
    handler: Handlers/handlerRDSupdate.RDSupdate
    events:
      - http:
          path: /RDSconnection/RDSupdate
          method: put
