

service: PrimerPost

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  servicioGET:
    handler: Handlers/handlerGET.servicioGET
    events:
      - http:
          path: /servicioGET
          method: get

  servicioPOST:
    handler: Handlers/handlerPOST.servicioPOST
    events:
      - http:
          path: /servicioPOST
          method: post        
