

service: PathParameters

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /pathParameters/{numero}
          method: get
