

service: HolaMundoAPI

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hola/mundo
          method: get
